### ISSUE TITLE
Inference, Error

### ISSUE THREAD

**Issue by th145** [dll-ncai/AI-ForestWatch#4]
Hi,
    I am trying to perform inference for abbotabad only using `python inference.py -dst abbotabad -y 2016` but I am getting this error:
```
Downloading: "https://download.pytorch.org/models/vgg11-8a719046.pth" to /root/.cache/torch/hub/checkpoints/vgg11-8a719046.pth
100% 507M/507M [00:02<00:00, 234MB/s]
LOG: Using pretrained convolutional layer Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


####################################################################################################
(LOG): The following Model Topology will be Utilized: ENC_4_DEC_4
####################################################################################################


UNet(
  (max_pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (dropout): Dropout2d(p=0.6, inplace=False)
  (activate): ReLU()
  (encoder_1): UNet_down_block(
    (conv1): Conv2d(18, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (encoder_2): UNet_down_block(
    (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (encoder_3): UNet_down_block(
    (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (encoder_4): UNet_down_block(
    (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (mid_conv_64_64_a): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_64_64_b): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_128_128_a): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_128_128_b): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_256_256_a): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_256_256_b): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_512_1024): Conv2d(512, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_1024_1024): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (decoder_4): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(1024, 1024, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(1536, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (decoder_3): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(256, 256, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(512, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (decoder_2): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(128, 128, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (decoder_1): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(64, 64, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (binary_last_conv): Conv2d(64, 2, kernel_size=(1, 1), stride=(1, 1))
  (softmax): Softmax(dim=1)
)
Trainable parameters: 30108866
Loading checkpoint: /content/gdrive/MyDrive/Forest_DAAD_Data/PretrainedModel/model_69_topologyENC_4_DEC_4_lr1e-06_bands18.pt ...
On District: mansehra @ Year: 2016
LOG: Generating data map now...
ERROR 4: /content/gdrive/MyDrive/Forest_DAAD_Data/inference/images/landsat8_2016_region_mansehra.tif: No such file or directory
Traceback (most recent call last):
  File "/content/AI-ForestWatch/inference.py", line 127, in <module>
    main(config, args)
  File "/content/AI-ForestWatch/inference.py", line 76, in main
    'inference_data_loader', module_data, image_path, district)
  File "/content/AI-ForestWatch/parse_config.py", line 103, in init_obj
    return getattr(module, module_name)(*args, **module_args)
  File "/content/AI-ForestWatch/data_loader/data_loaders.py", line 79, in __init__
    transformation=transforms)
  File "/content/AI-ForestWatch/base/base_dataset.py", line 127, in __init__
    x+1).ReadAsArray() for x in range(image_ds.RasterCount)]
AttributeError: 'NoneType' object has no attribute 'RasterCount'
```
What am I doing wrong here? Furthermore, why is it performing inference for `On District: mansehra @ Year: 2016`?

**I re-ran the same command for `hangu` and now I am getting this error:**
```
Downloading: "https://download.pytorch.org/models/vgg11-8a719046.pth" to /root/.cache/torch/hub/checkpoints/vgg11-8a719046.pth
100% 507M/507M [00:07<00:00, 73.9MB/s]
LOG: Using pretrained convolutional layer Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


####################################################################################################
(LOG): The following Model Topology will be Utilized: ENC_4_DEC_4
####################################################################################################


UNet(
  (max_pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (dropout): Dropout2d(p=0.6, inplace=False)
  (activate): ReLU()
  (encoder_1): UNet_down_block(
    (conv1): Conv2d(18, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (encoder_2): UNet_down_block(
    (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (encoder_3): UNet_down_block(
    (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (encoder_4): UNet_down_block(
    (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (mid_conv_64_64_a): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_64_64_b): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_128_128_a): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_128_128_b): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_256_256_a): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_256_256_b): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_512_1024): Conv2d(512, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_1024_1024): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (decoder_4): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(1024, 1024, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(1536, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (decoder_3): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(256, 256, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(512, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (decoder_2): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(128, 128, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (decoder_1): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(64, 64, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (binary_last_conv): Conv2d(64, 2, kernel_size=(1, 1), stride=(1, 1))
  (softmax): Softmax(dim=1)
)
Trainable parameters: 30108866
Loading checkpoint: /content/gdrive/MyDrive/Forest_DAAD_Data/PretrainedModel/model_69_topologyENC_4_DEC_4_lr1e-06_bands18.pt ...
On District: abbottabad @ Year: 2016
LOG: Generating data map now...
abbottabad: Band-0 Size: (2472, 2490)
Traceback (most recent call last):
  File "/content/AI-ForestWatch/inference.py", line 127, in <module>
    main(config, args)
  File "/content/AI-ForestWatch/inference.py", line 76, in main
    'inference_data_loader', module_data, image_path, district)
  File "/content/AI-ForestWatch/parse_config.py", line 103, in init_obj
    return getattr(module, module_name)(*args, **module_args)
  File "/content/AI-ForestWatch/data_loader/data_loaders.py", line 79, in __init__
    transformation=transforms)
  File "/content/AI-ForestWatch/base/base_dataset.py", line 131, in __init__
    district=district, this_landsat8_bands_list=all_raster_bands)
  File "/content/AI-ForestWatch/base/datagen.py", line 88, in mask_landsat8_image_using_rasterized_shapefile
    clipped_full_spectrum.append(np.multiply(this_band, shapefile_mask))
ValueError: operands could not be broadcast together with shapes (2472,2490) (2061,2075) 
```

**Comment by srinathjayaraman** [comment]
Hi! For the first error - it is most likely a GDAL issue. I faced the same problem yesterday while trying to run a different function from this repository. GDAL throws an error like this when it's not able to find the file/folder that's specified in your path. 

In the output you pasted, you can see the first error: ```ERROR 4: /content/gdrive/MyDrive/Forest_DAAD_Data/inference/images/landsat8_2016_region_mansehra.tif: No such file or directory```. 

And then below that you see the second error: ```AttributeError: 'NoneType' object has no attribute 'RasterCount'```.

This is happening because GDAL was not able to locate the file you want to analyze in the first place. Since it is returning ```None``` (literally nothing) from the path that's specified, it is obviously not going to have an attribute called ```RasterCount```.

I noticed that the path seems to be the same google drive link as in the original ```.py``` file. Download those files into directories in your local machine and run it again. If it doesn't work, check the file extension in cmd (command prompt) using the ```dir``` command. "TIFF" and "TIF" are considered to be different formats by GDAL (I don't know why), so that can also throw weird errors.

**Comment by srinathjayaraman** [comment]
Update - I'm facing the **second** error that you're facing. Pasting the relevant portions here:

```
Trainable parameters: 30108866

Loading checkpoint: C:\data\PretrainedModel\model_69_topologyENC_4_DEC_4_lr1e-06_bands18.pt ...

On District: malakand @ Year: 2016

LOG: Generating data map now...

malakand: Band-0 Size: (1321, 2692)

Traceback (most recent call last):  
File "C:\Users\sjayaramannaga\PycharmProjects\AI-ForestWatch-Srinath\inference.py", line 127, in <module>
    main(config, args)
  
File "C:\Users\sjayaramannaga\PycharmProjects\AI-ForestWatch-Srinath\inference.py", line 75, in main
    inference_loader = config.init_obj(
  
File "C:\Users\sjayaramannaga\PycharmProjects\AI-ForestWatch-Srinath\parse_config.py", line 103, in init_obj
    return getattr(module, module_name)(*args, **module_args)
  
File "C:\Users\sjayaramannaga\PycharmProjects\AI-ForestWatch-Srinath\data_loader\data_loaders.py", line 72, in __init__
    self.dataset = BaseInferenceDataset(rasterized_shapefiles_path=rasterized_shapefiles_path,
  
File "C:\Users\sjayaramannaga\PycharmProjects\AI-ForestWatch-Srinath\base\base_dataset.py", line 130, in __init__
    test_image, self.adjustment_mask = mask_landsat8_image_using_rasterized_shapefile(rasterized_shapefiles_path=rasterized_shapefiles_path,
  
File "C:\Users\sjayaramannaga\PycharmProjects\AI-ForestWatch-Srinath\base\datagen.py", line 89, in mask_landsat8_image_using_rasterized_shapefile
    clipped_full_spectrum.append(np.multiply(this_band, shapefile_mask))

ValueError: operands could not be broadcast together with shapes (1321,2692) (1101,2243)
```

**Comment by th145** [comment]
@srinathjayaraman Thank you for your reply!

**First Error:**

- I tried to check whether `image_ds` is None or not and it wasn't None. 

- I have saved images for some districts only on my Google Drive as there wasn't enough space. That is why I was performing inference for `Abbottabad` only. I am using Google Colab as I don't have GPU right now. But the problem is that when I was performing inference for `Abbottabad`,  I was getting inference for different districts `On District: mansehra @ Year: 2016`.. 

- I have named the directories the same as the authors have done. That's why the path is the same..

-  So, GDAL supports .tiff instead of .tif?

**Second Error:**
I didn't change anything, just re-ran the same command and got this error. Weird!



So, have you been able to resolve the issues?

**Comment by srinathjayaraman** [comment]
Well, the issue is that the 2 arrays being multiplied - ``` this_band``` and ```shapefile_mask``` are of different shapes. I am not sure how this ran for the original authors of the paper. Perhaps we are missing some data or maybe there is something wrong with the code. I am not quite sure yet!

Basically, the landsat8 image is slightly larger (as an array) than the shapefile. This makes sense, but not sure how the authors were able to get around this problem.

**Comment by srinathjayaraman** [comment]
@mohsin432 wondering if you could help us here? I saw you closed the issue I had opened a few weeks ago.

**Comment by th145** [comment]
@srinathjayaraman Yes, they are of different shapes which are causing this error. So, we both are getting the same error!
I hope the authors would resolve this problem.

**Comment by srinathjayaraman** [comment]
@th145 I have fixed the issue! 

So we identified the problem correctly. Trying to multiple 2 arrays that are of different shapes. This obviously will not work, no matter what function you try. I tried ```numpy.matmul``` and ```numpy.dot```, but they threw the same error as ```numpy.multiply```. The only way to fix this is to reshape or resize the array that represents the satellite image. There is already a function that exists in this repository! This is taken from lines 16 to 20 in ![base/datagen.py](https://github.com/dll-ncai/AI-ForestWatch/blob/d66d0a55db30a5010b83ddfc760cdf76b607f1a8/base/datagen.py#L16-L20)

```py
def adaptive_resize(array, new_shape):
    # reshape the labels to the size of the image
    single_band = Image.fromarray(array)
    single_band_resized = single_band.resize(new_shape, Image.NEAREST)
    return np.asarray(single_band_resized)
```
This function does the resizing for you, BEFORE the matrix multiplication happens. 

I don't know why it is missing from the updated code. In the ![old code folder](https://github.com/dll-ncai/AI-ForestWatch/tree/main/old%20code), there is an ![ìnference.py file](https://github.com/dll-ncai/AI-ForestWatch/blob/main/old%20code/inference.py). In line 51 of this file, you can see the ```adaptive_resize``` function is being called from the ```mask_landsat8_image_using_rasterized_shapefile``` function! The ![same old code folder](https://github.com/dll-ncai/AI-ForestWatch/tree/main/old%20code) has another file called ![dataset.py](https://github.com/dll-ncai/AI-ForestWatch/blob/8d0b26b90be0fe72575d3f470650308c74aae347/old%20code/dataset.py), and in line 102 of this file, the ```adaptive_resize``` function is being called again, this time from the ```get_images_from_large_file``` function! 

When they restructured the entire project, they removed the call to the ```adaptive_resize``` function from the ```mask_landsat8_image_using_rasterized_shapefile``` function. I have no idea why though. Anyway, I have attached proof that this works. You just need to add 2 lines of code:

Add the first line BEFORE defining ```clipped_full_spectrum```as a ```list()```:
```py
x_size, y_size = ds.RasterXSize, ds.RasterYSize
``` 

Add the second line INSIDE the loop (after the ```print``` statement) ```for idx, this_band in enumerate(all_raster_bands):```

 ```py
this_band = adaptive_resize(this_band, (x_size, y_size))
```
The image below shows how the raster band array is successfully resized BEFORE the matrix multiplication operation. I ran this function as a separate python script after making the 2 modifications listed above, and it ran successfully.

![reshape](https://user-images.githubusercontent.com/11828799/188195859-332ed905-6f11-4f05-b27b-e016993ce2b0.PNG)

**Comment by srinathjayaraman** [comment]
@th145 there are some differences between the old ```mask_landsat8_image_using_rasterized_shapefile``` function in the ```old code``` folder versus the new ```mask_landsat8_image_using_rasterized_shapefile``` function in the ```datagen.py``` file.

```old code_inference.py```:

```py
def mask_landsat8_image_using_rasterized_shapefile(rasterized_shapefiles_path, district, this_landsat8_bands_list):
    this_shapefile_path = os.path.join(rasterized_shapefiles_path, "{}_shapefile.tif".format(district))
    ds = gdal.Open(this_shapefile_path)
    assert ds.RasterCount == 1
    shapefile_mask = np.array(ds.GetRasterBand(1).ReadAsArray(), dtype=np.uint8)
    x_size, y_size = ds.RasterXSize, ds.RasterYSize
    clipped_full_spectrum = list()
    for idx, this_band in enumerate(this_landsat8_bands_list):
        print("{}: Band-{} Size: {}".format(district, idx, this_band.shape))
        this_band = adaptive_resize(this_band, (x_size, y_size))
        clipped_full_spectrum.append(np.multiply(this_band, shapefile_mask))
    x_prev, y_prev = clipped_full_spectrum[0].shape
    x_fixed, y_fixed = int(128 * np.ceil(x_prev / 128)), int(128 * np.ceil(y_prev / 128))
    diff_x, diff_y = x_fixed - x_prev, y_fixed - y_prev
    diff_x_before, diff_y_before = diff_x//2, diff_y//2
    clipped_full_spectrum_resized = [np.pad(x, [(diff_x_before, diff_x-diff_x_before), (diff_y_before, diff_y-diff_y_before)], mode='constant')
                                     for x in clipped_full_spectrum]
    clipped_shapefile_mask_resized = np.pad(shapefile_mask, [(diff_x_before, diff_x-diff_x_before), (diff_y_before, diff_y-diff_y_before)], mode='constant')
    clipped_full_spectrum_stacked_image = np.dstack(clipped_full_spectrum_resized)
    print("{}: Generated Image Size: {}".format(district, clipped_full_spectrum_stacked_image.shape))
    return clipped_full_spectrum_stacked_image, clipped_shapefile_mask_resized
```

```new code_datagen.py```

```py
def mask_landsat8_image_using_rasterized_shapefile(rasterized_shapefiles_path, district, this_landsat8_bands_list):
    this_shapefile_path = os.path.join(
        rasterized_shapefiles_path, "{}_shapefile.tif".format(district))
    ds = gdal.Open(this_shapefile_path)
    assert ds.RasterCount == 1
    shapefile_mask = np.array(ds.GetRasterBand(1).ReadAsArray(), dtype=np.uint8)
    clipped_full_spectrum = list()
    for idx, this_band in enumerate(this_landsat8_bands_list):
        print("{}: Band-{} Size: {}".format(district, idx, this_band.shape))
        clipped_full_spectrum.append(np.multiply(this_band, shapefile_mask))
    x_prev, y_prev = clipped_full_spectrum[0].shape
    x_fixed, y_fixed = int(128 * np.ceil(x_prev / 128)), int(128 * np.ceil(y_prev / 128))
    diff_x, diff_y = x_fixed - x_prev, y_fixed - y_prev
    diff_x_before, diff_y_before = diff_x // 2, diff_y // 2
    clipped_full_spectrum_resized = [np.pad(x, [(diff_x_before, diff_x - diff_x_before), (diff_y_before, diff_y - diff_y_before)], mode='constant') for x in clipped_full_spectrum]
    print("{}: Generated Image Size: {}".format(
        district, clipped_full_spectrum_resized[0].shape, len(clipped_full_spectrum_resized)))
    return clipped_full_spectrum_resized
```

The newer function returns one less variable. Not sure what happened to the old way of doing this. The ```inference.py``` file will still fail when you run it. although after fixing the matrix multiplication issue, it is now failing with ```ValueError: too many values to unpack (expected 2)``` in line 128 of ```base_dataset.py```.

Looking into this.

**Comment by th145** [comment]
@srinathjayaraman Thank you for resolving the issue to some extent. 
You are right it's still throwing an error:
```
LOG: Using pretrained convolutional layer Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
LOG: Using pretrained convolutional layer Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


####################################################################################################
(LOG): The following Model Topology will be Utilized: ENC_4_DEC_4
####################################################################################################


UNet(
  (max_pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (dropout): Dropout2d(p=0.6, inplace=False)
  (activate): ReLU()
  (encoder_1): UNet_down_block(
    (conv1): Conv2d(18, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (encoder_2): UNet_down_block(
    (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (encoder_3): UNet_down_block(
    (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (encoder_4): UNet_down_block(
    (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (mid_conv_64_64_a): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_64_64_b): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_128_128_a): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_128_128_b): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_256_256_a): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_256_256_b): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_512_1024): Conv2d(512, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mid_conv_1024_1024): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (decoder_4): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(1024, 1024, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(1536, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (decoder_3): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(256, 256, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(512, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (decoder_2): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(128, 128, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (decoder_1): UNet_up_block(
    (tr_conv_1): ConvTranspose2d(64, 64, kernel_size=(2, 2), stride=(2, 2))
    (conv_1): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activate): ReLU()
  )
  (binary_last_conv): Conv2d(64, 2, kernel_size=(1, 1), stride=(1, 1))
  (softmax): Softmax(dim=1)
)
Trainable parameters: 30108866
Loading checkpoint: /content/gdrive/MyDrive/Forest_DAAD_Data/PretrainedModel/model_69_topologyENC_4_DEC_4_lr1e-06_bands18.pt ...
On District: hangu @ Year: 2016
LOG: Generating data map now...
hangu: Band-0 Size: (1788, 3322)
hangu: Band-1 Size: (1788, 3322)
hangu: Band-2 Size: (1788, 3322)
hangu: Band-3 Size: (1788, 3322)
hangu: Band-4 Size: (1788, 3322)
hangu: Band-5 Size: (1788, 3322)
hangu: Band-6 Size: (1788, 3322)
hangu: Band-7 Size: (1788, 3322)
hangu: Band-8 Size: (1788, 3322)
hangu: Band-9 Size: (1788, 3322)
hangu: Band-10 Size: (1788, 3322)
hangu: Generated Image Size: (1536, 2816)
Traceback (most recent call last):
  File "/content/AI-ForestWatch/inference.py", line 127, in <module>
    main(config, args)
  File "/content/AI-ForestWatch/inference.py", line 76, in main
    'inference_data_loader', module_data, image_path, district)
  File "/content/AI-ForestWatch/parse_config.py", line 103, in init_obj
    return getattr(module, module_name)(*args, **module_args)
  File "/content/AI-ForestWatch/data_loader/data_loaders.py", line 79, in __init__
    transformation=transforms)
  File "/content/AI-ForestWatch/base/base_dataset.py", line 131, in __init__
    district=district, this_landsat8_bands_list=all_raster_bands)
ValueError: too many values to unpack (expected 2)
```
One more thing that I observed is that when I pass optional arguments, it still performs the inference for all the districts. For example, if I write:
`python inference.py -dst 'abbottabad' -y 2016` 
then it performs inference for some random district. In the above case, it was performed for Hangu. Again weird!
